name: equivalent-list
version: 0.1.0.0

library:
  source-dirs: .
  exposed-modules:
    - EquivalentList

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/equivalent-list

dependencies:
  - base >= 4.9 && < 4.10

ghc-options:
  - -Wall

tests:
  doctest:
    source-dirs: .
    main: doctest.hs
    dependencies:
      - doctest
      - equivalent-list
    ghc-options:
      - -threaded
