name: equivalent-list
version: 0.1.0.0

library:
  source-dirs: src
  exposed-modules:
    - EquivalentList

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/haskell-libraries

dependencies:
  - base >= 4.9 && < 4.10

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude

tests:
  doctest:
    source-dirs: test
    main: doctest.hs
    dependencies:
      - doctest
      - equivalent-list
    ghc-options:
      - -threaded
